
$FullPath='C:\Users\10628594\Desktop\testausgaben\Zusammen.html'

 
#Get an Outlook application object
 
$o = New-Object -com Outlook.Application
 
$mail = $o.CreateItem(0)
 
#2 = High importance message
$mail.importance = 2
 
$mail.subject = "This is the subject of the mail"
$mail.body = "This is the body of the email. It has been automatically generated by a script."
 
#separate multiple recipients with a ";"
$mail.To = "abhiarn@gmx.de"
#$mail.CC = <OTHER RECIPIENT 1>;<OTHER RECIPIENT 2>
 
# Iterate over all files and only add the ones that have an .html extension
$files = Get-ChildItem $FullPath
 
for ($i=0; $i -lt $files.Count; $i++) {
 
$outfileName = $files[$i].FullName
$outfileNameExtension = $files[$i].Extension
 
# if the extension is the one we want, add to attachments
if($outfileNameExtension -eq ".html")
{
$mail.Attachments.Add($outfileName);
}
}
$mail.Send()
 